# This is a basic workflow to help you get started with Actions

name: Buildroot

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download dependencies
        run: |
          sudo apt install wget gcc perl rsync make build-essential bc
      
      - name: Create Buildroot directory, download and extract
        run: |
          wget https://buildroot.org/downloads/buildroot-2021.05.tar.bz2
          tar xf buildroot-2021.05.tar.bz2
      
      - name: Copy configuration file
        run: |
          cp $GITHUB_WORKSPACE/Buildroot/.config $GITHUB_WORKSPACE/buildroot-2021.05
          
      - name: Build buildroot image
        run: |
          cd $GITHUB_WORKSPACE/buildroot-2021.05
          make all
    

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: image
          # A file, directory or wildcard pattern that describes what to upload
          path: $GITHUB_WORKSPACE/buildroot-2021.05/output/images/sdcard.img
