name: t2Build
on:
 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  
  workflow_dispatch:


jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
         sudo apt update
         sudo apt upgrade
         sudo apt-get install git rsync cmake subversion gcc
         
      - name: Checkout t2sde subversion repo
        run: |
         svn co http://svn.exactcode.de/t2/trunk t2-trunk -q
         cd t2-trunk

         svn switch http://svn.exactcode.de/t2/tags/21.7
        
        

