name: t2Build
on:
 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  
  workflow_dispatch:


jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - run: |
         sudo apt update
         sudo apt upgrade
         sudo apt-get install git rsync cmake subversion gcc
         

         svn co http://svn.exactcode.de/t2/trunk t2-trunk -q
         cd t2-trunk

         svn switch http://svn.exactcode.de/t2/tags/21.7
         echo To be completed
        
        

